Import Upstream version 2.14

diff --git a/tests/util/grub-shell.in b/tests/util/grub-shell.in
--- a/tests/util/grub-shell.in
+++ b/tests/util/grub-shell.in
@@ -74,7 +74,8 @@ exec_show_error () {
 work_directory=${WORKDIR:-`mktemp -d "${TMPDIR:-/tmp}/grub-shell.XXXXXXXXXX"`} || exit 1
 
 . "${builddir}/grub-core/modinfo.sh"
-qemuopts=
+qemuopts=${GRUB_QEMU_OPTS}
+emuopts=
 serial_port=com0
 serial_null=
 halt_cmd=halt
@@ -181,21 +182,92 @@ case "${grub_modinfo_target_cpu}-${grub_modinfo_platform}" in
 	boot=cd
 	console=console
 	trim=1
-	qemuopts="-bios OVMF-ia32.fd $qemuopts"
+	pflash=${srcdir}/OVMF32.fd
+	pflash_code=${srcdir}/OVMF32_CODE.fd
+	pflash_vars=${srcdir}/OVMF32_VARS.fd
+	if [ -f "$pflash" ]; then
+	    qemuopts="-drive if=pflash,format=raw,unit=0,snapshot=on,file=$pflash $qemuopts"
+	elif [ -f "$pflash_code" ]; then
+	    qemuopts="-drive if=pflash,format=raw,unit=0,readonly=on,file=$pflash_code $qemuopts"
+	    if [ -f "$pflash_vars" ]; then
+		qemuopts="-drive if=pflash,format=raw,unit=1,snapshot=on,file=$pflash_vars $qemuopts"
+	    fi
+	else
+	    pflash=/usr/share/qemu/OVMF32.fd
+	    pflash_code=/usr/share/OVMF/OVMF32_CODE_4M.secboot.fd
+	    pflash_vars=/usr/share/OVMF/OVMF32_VARS_4M.fd
+	    if [ -f "$pflash" ]; then
+		qemuopts="-drive if=pflash,format=raw,unit=0,snapshot=on,file=$pflash $qemuopts"
+	    elif [ -f "$pflash_code" ]; then
+		qemuopts="-drive if=pflash,format=raw,unit=0,readonly=on,file=$pflash_code $qemuopts"
+		qemuopts="-drive if=pflash,format=raw,unit=1,snapshot=on,file=$pflash_vars $qemuopts"
+	    else
+		echo "Firmware not found, please install either the appropriate Debian package or an appropriately named copy in the source directory." >&2
+		exit 1
+	    fi
+	fi
+	qemuopts="-machine q35 $qemuopts"
 	;;
     x86_64-efi)
 	qemu=qemu-system-x86_64
 	boot=cd
 	console=console
 	trim=1
-	qemuopts="-bios OVMF.fd $qemuopts"
+	pflash=${srcdir}/OVMF.fd
+	pflash_code=${srcdir}/OVMF_CODE.fd
+	pflash_vars=${srcdir}/OVMF_VARS.fd
+	if [ -f "$pflash" ]; then
+	    qemuopts="-drive if=pflash,format=raw,unit=0,snapshot=on,file=$pflash $qemuopts"
+	elif [ -f "$pflash_code" ]; then
+	    qemuopts="-drive if=pflash,format=raw,unit=0,readonly=on,file=$pflash_code $qemuopts"
+	    if [ -f "$pflash_vars" ]; then
+		qemuopts="-drive if=pflash,format=raw,unit=1,snapshot=on,file=$pflash_vars $qemuopts"
+	    fi
+	else
+	    pflash=/usr/share/qemu/OVMF.fd
+	    pflash_code=/usr/share/OVMF/OVMF_CODE.fd
+	    pflash_vars=/usr/share/OVMF/OVMF_VARS.fd
+	    if [ -f "$pflash" ]; then
+		qemuopts="-drive if=pflash,format=raw,unit=0,snapshot=on,file=$pflash $qemuopts"
+	    elif [ -f "$pflash_code" ]; then
+		qemuopts="-drive if=pflash,format=raw,unit=0,readonly=on,file=$pflash_code $qemuopts"
+		qemuopts="-drive if=pflash,format=raw,unit=1,snapshot=on,file=$pflash_vars $qemuopts"
+	    else
+		echo "Firmware not found, please install either the appropriate Debian package or an appropriately named copy in the source directory." >&2
+		exit 1
+	    fi
+	fi
 	;;
     arm64-efi)
 	qemu=qemu-system-aarch64
 	boot=hd
 	console=console
 	trim=1
-	qemuopts="-machine virt -cpu cortex-a57 -bios /usr/share/qemu-efi/QEMU_EFI.fd $qemuopts"
+	pflash=${srcdir}/AAVMF.fd
+	pflash_code=${srcdir}/AAVMF_CODE.fd
+	pflash_vars=${srcdir}/AAVMF_VARS.fd
+	if [ -f "$pflash" ]; then
+	    qemuopts="-drive if=pflash,format=raw,unit=0,snapshot=on,file=$pflash $qemuopts"
+	elif [ -f "$pflash_code" ]; then
+	    qemuopts="-drive if=pflash,format=raw,unit=0,readonly=on,file=$pflash_code $qemuopts"
+	    if [ -f "$pflash_vars" ]; then
+		qemuopts="-drive if=pflash,format=raw,unit=1,snapshot=on,file=$pflash_vars $qemuopts"
+	    fi
+	else
+	    pflash=/usr/share/qemu-efi-aarch64/QEMU_EFI.fd
+	    pflash_code=/usr/share/AAVMF/AAVMF_CODE.fd
+	    pflash_vars=/usr/share/AAVMF/AAVMF_VARS.fd
+	    if [ -f "$pflash" ]; then
+		qemuopts="-drive if=pflash,format=raw,unit=0,snapshot=on,file=$pflash $qemuopts"
+	    elif [ -f "$pflash_code" ]; then
+		qemuopts="-drive if=pflash,format=raw,unit=0,readonly=on,file=$pflash_code $qemuopts"
+		qemuopts="-drive if=pflash,format=raw,unit=1,snapshot=on,file=$pflash_vars $qemuopts"
+	    else
+		echo "Firmware not found, please install either the appropriate Debian package or an appropriately named copy in the source directory." >&2
+		exit 1
+	    fi
+	fi
+	qemuopts="-machine virt -cpu cortex-a57 $qemuopts"
 	disk="device virtio-blk-device,drive=hd1 -drive if=none,id=hd1,file="
 	serial_port=
 	;;
@@ -204,7 +276,31 @@ case "${grub_modinfo_target_cpu}-${grub_modinfo_platform}" in
 	boot=hd
 	console=console
 	trim=1
-	qemuopts="-machine virt -bios /usr/share/ovmf-arm/QEMU_EFI.fd $qemuopts"
+	pflash=${srcdir}/AAVMF32.fd
+	pflash_code=${srcdir}/AAVMF32_CODE.fd
+	pflash_vars=${srcdir}/AAVMF32_VARS.fd
+	if [ -f "$pflash" ]; then
+	    qemuopts="-drive if=pflash,format=raw,unit=0,snapshot=on,file=$pflash $qemuopts"
+	elif [ -f "$pflash_code" ]; then
+	    qemuopts="-drive if=pflash,format=raw,unit=0,readonly=on,file=$pflash_code $qemuopts"
+	    if [ -f "$pflash_vars" ]; then
+		qemuopts="-drive if=pflash,format=raw,unit=1,snapshot=on,file=$pflash_vars $qemuopts"
+	    fi
+	else
+	    pflash=/usr/share/AAVMF/AAVMF32.fd
+	    pflash_code=/usr/share/AAVMF/AAVMF32_CODE.fd
+	    pflash_vars=/usr/share/AAVMF/AAVMF32_VARS.fd
+	    if [ -f "$pflash" ]; then
+		qemuopts="-drive if=pflash,format=raw,unit=0,snapshot=on,file=$pflash $qemuopts"
+	    elif [ -f "$pflash_code" ]; then
+		qemuopts="-drive if=pflash,format=raw,unit=0,readonly=on,file=$pflash_code $qemuopts"
+		qemuopts="-drive if=pflash,format=raw,unit=1,snapshot=on,file=$pflash_vars $qemuopts"
+	    else
+		echo "Firmware not found, please install either the appropriate Debian package or an appropriately named copy in the source directory." >&2
+		exit 1
+	    fi
+	fi
+	qemuopts="-machine virt $qemuopts"
 	disk="device virtio-blk-device,drive=hd1 -drive if=none,id=hd1,file="
 	serial_port=efi0
 	;;
@@ -281,6 +377,9 @@ for option in "$@"; do
     --qemu-opts=*)
 	qs=`echo "$option" | sed -e 's/--qemu-opts=//'`
 	qemuopts="$qemuopts $qs" ;;
+    --emu-opts=*)
+	qs=`echo "$option" | sed -e 's/--emu-opts=//'`
+	emuopts="$emuopts $qs" ;;
     --disk=*)
 	dsk=`echo "$option" | sed -e 's/--disk=//'`
 	if [ ${grub_modinfo_platform} = emu ]; then
@@ -360,6 +459,9 @@ halt_cmd=${halt_cmd}
 export halt_cmd
 enable_progress_indicator=0
 export enable_progress_indicator
+if [ "${grub_modinfo_platform}" == efi ]; then
+  gdbinfo
+fi
 EOF
 
 
@@ -576,7 +678,7 @@ elif [ x$boot = xemu ]; then
     cat >"$work_directory/run.sh" <<EOF
 #! @BUILD_SHEBANG@
 SDIR=\$(realpath -e \${0%/*})
-exec "$(realpath -e "${builddir}")/grub-core/grub-emu" -m "\$SDIR/${device_map##*/}" --memdisk "\$SDIR/${roottar##*/}" -r memdisk -d "/boot/grub"
+exec "$(realpath -e "${builddir}")/grub-core/grub-emu" -m "\$SDIR/${device_map##*/}" --memdisk "\$SDIR/${roottar##*/}" -r memdisk -d "/boot/grub" ${emuopts}
 EOF
 else
     cat >"$work_directory/run.sh" <<EOF
@@ -609,10 +711,14 @@ elif [ x$boot = xemu ]; then
     test -n "$debug" || rm -rf "$rootdir"
     test -n "$debug" || rm -f "$roottar"
 fi
+if [ x$boot = xnet ]; then
+    test -n "$debug" || rm -rf "$work_directory/netdir"
+fi
 test -n "$debug" || rm -f "${isofile}"
 test -n "$debug" || rm -rf "${rom_directory}"
 test -n "$debug" || rm -f "${tmpfile}" "${cfgfile}" "${goutfile}"
 test -n "$debug" || rm -f "$work_directory/run.sh"
+test -n "$debug" || rmdir "$work_directory"
 
 exit $ret
 
